/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaodienmain;

import dangnhap.Dangnhap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;





/**
 *
 * @author 84868
 */
public class MainManage extends javax.swing.JFrame {

    /**
     * Creates new form MainManage
     */
    public MainManage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        Dangnhap = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        Quanlynhansu = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        Danhsachnhansu = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        Thoat = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ NHÂN SỰ");

        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator4);

        Dangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login-icon-48.png"))); // NOI18N
        Dangnhap.setText("Đăng nhập");
        Dangnhap.setFocusable(false);
        Dangnhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Dangnhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangnhapActionPerformed(evt);
            }
        });
        jToolBar1.add(Dangnhap);
        jToolBar1.add(jSeparator5);

        Quanlynhansu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Person-Male-Light-icon-48.png"))); // NOI18N
        Quanlynhansu.setText("Quản lý nhân sự");
        Quanlynhansu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Quanlynhansu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Quanlynhansu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanlynhansuActionPerformed(evt);
            }
        });
        jToolBar1.add(Quanlynhansu);
        jToolBar1.add(jSeparator6);

        Danhsachnhansu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-edit-icon-48.png"))); // NOI18N
        Danhsachnhansu.setText("Danh sách nhân sự");
        Danhsachnhansu.setFocusable(false);
        Danhsachnhansu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Danhsachnhansu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Danhsachnhansu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DanhsachnhansuActionPerformed(evt);
            }
        });
        jToolBar1.add(Danhsachnhansu);
        jToolBar1.add(jSeparator7);

        Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-48.png"))); // NOI18N
        Thoat.setText("Thoát");
        Thoat.setFocusable(false);
        Thoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Thoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatActionPerformed(evt);
            }
        });
        jToolBar1.add(Thoat);
        jToolBar1.add(jSeparator8);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nhóm 11.PNG"))); // NOI18N

        jMenuBar1.setToolTipText("");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuanlynhansuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanlynhansuActionPerformed
        // MainForm1 obj = new MainForm1();
        //obj.setVisible(true);
        
    }//GEN-LAST:event_QuanlynhansuActionPerformed

    private void DanhsachnhansuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DanhsachnhansuActionPerformed
        // MainForm obj = new MainForm();
        //obj.setVisible(true);
        
    }//GEN-LAST:event_DanhsachnhansuActionPerformed

    private void ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatActionPerformed
        JFrame frame = new JFrame("Swing Tester");
        int result = JOptionPane.showConfirmDialog(frame,
                        "Bạn có chắc muốn thoát",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if(result == JOptionPane.YES_OPTION){
                    System.exit(0);
           }
        
    }//GEN-LAST:event_ThoatActionPerformed

    private void DangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangnhapActionPerformed
        new Dangnhap().setVisible(true);
    }//GEN-LAST:event_DangnhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dangnhap;
    private javax.swing.JButton Danhsachnhansu;
    private javax.swing.JButton Quanlynhansu;
    private javax.swing.JButton Thoat;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
